### ISSUE TITLE
Build not correctly setting index.html css file to minimized version

### ISSUE THREAD

**Issue by tydanielson** [LogMeIn-BoldChat/Html-Chat-Sdk#8]
When I run the following command to build a production version of the chat client:
`gulp --prod --min --minhtml`
Everything appears to work, files are minimized and compressed, but when the injection of the file in the index.html and popup.html happens, only the js file is written in.  The css file continues to be set as the original version.  This happens for all themes and not just the custom one I'm working on.

**Comment by boldwade** [comment]
Hi Ty! Sorry for the delay on getting back to you, things have been busy here. You'll notice in the last push, a fix for what you have identified. I've also updated and added a few gulp packages so you'll need to run npm install again. The issue was that the source for the css file was pointed at ./src instead of ./out. This has been corrected. Thanks for pointing it out!
